spider:
  config:
    autoProxy: false
    initialDelay: 0
    maxRetries: 3
    retryDelayMillis: 1000
    useConsolePipeline: true

  request:
    sleepTime: 0
    autoSleepTime: false
    downloadDelay: 0
    autoDownloadDelay: false
    domainDelay: 0
    autoDomainDelay: false

  queue:
    # default、disruptor
    type: default

  pipeline:
    pipelineDelay: 0
    autoPipelineDelay: false

  downloader:
    # vertx、urlConnection、file
    type: vertx
    vertx:
      options:
        keepAlive: true
        reuseAddress: true
        followRedirects: true
        connectTimeout: 10000
        idleTimeout: 10
        maxWaitQueueSize: 10

spiderEngine:
  config:
    port: 8715
    useMonitor: true